<?php

return [
    'routes' => [
        '/' => [AuthController::class, 'login'],
        '/login' => [AuthController::class, 'login'],
        '/logout' => [AuthController::class, 'logout'],
        '/kasir' => [DashboardController::class, 'kasir'],
        '/owner' => [DashboardController::class, 'owner'],
        '/transactions' => [TransactionController::class, 'index'],
        '/transactions/create' => [TransactionController::class, 'create'],
        '/transactions/categories' => [
            TransactionController::class,
            'categories',
        ],
        '/transactions/variants' => [TransactionController::class, 'getVariants'],
        '/transactions/variant-options' => [TransactionController::class, 'getVariantOptions'],
        '/transactions/sablon-types' => [TransactionController::class, 'getSablonTypes'],
        '/transactions/calculate-price' => [TransactionController::class, 'calculatePrice'],
        '/transactions/validate-quantity' => [TransactionController::class, 'validateQuantity'],
        '/transactions/customer/save' => [TransactionController::class, 'saveCustomerData'],
        '/transactions/customer' => [TransactionController::class, 'getCustomerData'],
        '/transactions/cart' => [TransactionController::class, 'cart'],
        '/transactions/detail' => [TransactionController::class, 'detail'],
        '/transactions/invoice' => [TransactionController::class, 'invoice'],

        '/transactions/store' => [TransactionController::class, 'store'],
        '/transactions/delete-design' => [
            TransactionController::class,
            'deleteDesign',
        ],
        '/transactions/update-design' => [
            TransactionController::class,
            'updateDesign',
        ],
        '/transactions/record-payment' => [
            TransactionController::class,
            'recordPayment',
        ],
        '/transactions/update-status' => [
            TransactionController::class,
            'updateStatus',
        ],
        '/transactions/void-payment' => [
            TransactionController::class,
            'voidPayment',
        ],
        '/transactions/refund-payment' => [
            TransactionController::class,
            'refundPayment',
        ],
        '/transactions/form/tshirt' => [TransactionController::class, 'tshirt'],
        '/transactions/form/t-shirt' => [TransactionController::class, 'tshirt'],
        '/transactions/form/pdh' => [TransactionController::class, 'pdh'],
        '/transactions/form/jersey' => [TransactionController::class, 'jersey'],
        '/transactions/form/poloshirt' => [TransactionController::class, 'poloshirt'],
        '/transactions/form/polo-shirt' => [TransactionController::class, 'poloshirt'],
        '/transactions/form/seragamolahraga' => [TransactionController::class, 'seragamolahraga'],
        '/transactions/form/sports-uniform' => [TransactionController::class, 'seragamolahraga'],
        '/transactions/form/jacket' => [TransactionController::class, 'jacket'],
        '/transactions/form/hoodie' => [TransactionController::class, 'hoodie'],
        '/products' => [ProductController::class, 'index'],
        '/products/store' => [ProductController::class, 'store'],
        '/products/update' => [ProductController::class, 'update'],
        '/products/destroy' => [ProductController::class, 'destroy'],
        '/products/destroy-batch' => [ProductController::class, 'destroyBatch'],
        '/products/toggle-active' => [ProductController::class, 'toggleActive'],
        '/products/destroy-option' => [
            ProductController::class,
            'destroyOption',
        ],
        '/products/toggle-option-status' => [ProductController::class, 'toggleOptionStatus'],
        '/products/variant-options' => [ProductController::class, 'variantOptions'],
        '/products/variant-options/store' => [ProductController::class, 'storeVariantOption'],
        '/products/variant-options/update' => [ProductController::class, 'updateVariantOption'],
        '/products/variant-options/toggle' => [ProductController::class, 'toggleVariantOptionStatus'],
        '/products/update-quantity' => [ProductController::class, 'updateQuantity'],
        '/products/manage-category' => [
            ProductController::class,
            'manageCategory',
        ],
        '/products/manage-product' => [
            ProductController::class,
            'manageProduct',
        ],
        '/products/by-category' => [ProductController::class, 'byCategory'],
        '/products/manage-size' => [ProductController::class, 'manageSize'],
        '/products/manage-color' => [ProductController::class, 'manageColor'],
        '/products/manage-sablon-type' => [ProductController::class, 'manageSablonType'],
        '/products/sablon-types' => [ProductController::class, 'sablonTypes'],
        '/products/sablon-types/store' => [ProductController::class, 'storeSablonType'],
        '/products/sablon-types/update' => [ProductController::class, 'updateSablonType'],
        '/products/sablon-types/toggle' => [ProductController::class, 'toggleSablonTypeStatus'],
        '/products/sablon-types/add-category' => [ProductController::class, 'addSablonCategory'],
        '/products/sablon-types/remove-category' => [ProductController::class, 'removeSablonCategory'],
        '/finance' => [PenjualanController::class, 'index'],
    ],

    'public' => ['/login', '/logout', '/'],

    'roles' => [
        '/kasir' => [Model::ROLE_KASIR],
        '/owner' => [Model::ROLE_OWNER],

        '/transactions' => [Model::ROLE_KASIR, Model::ROLE_OWNER],
        '/transactions/detail' => [Model::ROLE_KASIR, Model::ROLE_OWNER],
        '/transactions/invoice' => [Model::ROLE_KASIR, Model::ROLE_OWNER],

        '/transactions/create' => [Model::ROLE_KASIR],
        '/transactions/categories' => [Model::ROLE_KASIR],
        '/transactions/variants' => [Model::ROLE_KASIR],
        '/transactions/variant-options' => [Model::ROLE_KASIR],
        '/transactions/sablon-types' => [Model::ROLE_KASIR],
        '/transactions/calculate-price' => [Model::ROLE_KASIR],
        '/transactions/validate-quantity' => [Model::ROLE_KASIR],
        '/transactions/customer/save' => [Model::ROLE_KASIR],
        '/transactions/customer' => [Model::ROLE_KASIR],
        '/transactions/cart' => [Model::ROLE_KASIR],

        '/transactions/store' => [Model::ROLE_KASIR],
        '/transactions/delete-design' => [Model::ROLE_KASIR],
        '/transactions/update-design' => [Model::ROLE_KASIR],
        '/transactions/record-payment' => [Model::ROLE_KASIR, Model::ROLE_OWNER],
        '/transactions/update-status' => [Model::ROLE_KASIR, Model::ROLE_OWNER],
        '/transactions/void-payment' => [Model::ROLE_KASIR, Model::ROLE_OWNER],
        '/transactions/refund-payment' => [Model::ROLE_OWNER],
        '/transactions/form/tshirt' => [Model::ROLE_KASIR],
        '/transactions/form/t-shirt' => [Model::ROLE_KASIR],
        '/transactions/form/pdh' => [Model::ROLE_KASIR],
        '/transactions/form/jersey' => [Model::ROLE_KASIR],
        '/transactions/form/poloshirt' => [Model::ROLE_KASIR],
        '/transactions/form/polo-shirt' => [Model::ROLE_KASIR],
        '/transactions/form/seragamolahraga' => [Model::ROLE_KASIR],
        '/transactions/form/sports-uniform' => [Model::ROLE_KASIR],
        '/transactions/form/jacket' => [Model::ROLE_KASIR],
        '/transactions/form/hoodie' => [Model::ROLE_KASIR],
        '/products' => [Model::ROLE_OWNER],
        '/products/store' => [Model::ROLE_OWNER],
        '/products/update' => [Model::ROLE_OWNER],
        '/products/destroy' => [Model::ROLE_OWNER],
        '/products/destroy-batch' => [Model::ROLE_OWNER],
        '/products/toggle-active' => [Model::ROLE_OWNER],
        '/products/destroy-option' => [Model::ROLE_OWNER],
        '/products/toggle-option-status' => [Model::ROLE_OWNER],
        '/products/variant-options' => [Model::ROLE_OWNER],
        '/products/variant-options/store' => [Model::ROLE_OWNER],
        '/products/variant-options/update' => [Model::ROLE_OWNER],
        '/products/variant-options/toggle' => [Model::ROLE_OWNER],
        '/products/update-quantity' => [Model::ROLE_OWNER],
        '/products/manage-category' => [Model::ROLE_OWNER],
        '/products/manage-product' => [Model::ROLE_OWNER],
        '/products/by-category' => [Model::ROLE_OWNER],
        '/products/manage-size' => [Model::ROLE_OWNER],
        '/products/manage-color' => [Model::ROLE_OWNER],
        '/products/manage-sablon-type' => [Model::ROLE_OWNER],
        '/products/sablon-types' => [Model::ROLE_OWNER],
        '/products/sablon-types/store' => [Model::ROLE_OWNER],
        '/products/sablon-types/update' => [Model::ROLE_OWNER],
        '/products/sablon-types/toggle' => [Model::ROLE_OWNER],
        '/products/sablon-types/add-category' => [Model::ROLE_OWNER],
        '/products/sablon-types/remove-category' => [Model::ROLE_OWNER],
        '/finance' => [Model::ROLE_OWNER],
    ],
];
